### ISSUE TITLE
region of interest shows variance 0 ... Error using dlmread

### ISSUE THREAD

**Issue by Koushouu** [alisterburt/autoalign_dynamo#4]
Hi, I am going through the tutorial as posted on teamtomo.org (https://teamtomo.org/walkthroughs/EMPIAR-10164/tilt-series-to-tomograms.html) I am currently at Aligning the tilt series step.
I got an error while running "dautoalign4warp('./imod', 1.35, 10, 85.3, './dynamo_alignments')" on matlab. It gives error like the following:

---
...
[mbparse.multicore.checkPool] ... opened pool for 16 workers in 39.11 seconds
[normalize_roi] Warning: region of interest shows variance 0 (mean:0.000000)
NaN detected when computed maximum of the volume!!!
Attention: could not locate peak: empty result! 
Warning: Index exceeds the number of array elements (0). 
> In autoalign_warn (line 7)
  In handle_exception (line 10)
  In dautoalign4warp (line 32) 
Warning: Attempting to continue... 
> In autoalign_warn (line 7)
  In handle_exception (line 11)
  In dautoalign4warp (line 32) 
Warning: File 'tmp.csv' not found. 
> In autoalign_aux_cleanup (line 2)
  In dautoalign4warp (line 34) 
cat: './dynamo_alignments/*/info/fitting.doc': No such file or directory
Error using dlmread (line 147)
Empty format character vector is not supported at the end of a file.

Error in csvread (line 48)
    m=dlmread(filename, ',', r, c);

Error in autoalign_summarise (line 7)
    m = csvread(fullfile(output_folder, 'rms.txt'));

Error in dautoalign4warp (line 35)
            autoalign_summarise(output_folder)

---
full log here: https://drive.google.com/file/d/1KmRoAQ18hNFHyU6zwo2pGp2H-w-Na4RA/view?usp=sharing
Do you know what might be the problem?
I am using
IMOD 4.12.10
Matlab R2020a
Dynamo v-1.1.514

The previous operation with WARP was done in a Windows environment, and data was transferred to a Linux machine (Ubuntu 16.04) for this particular step.

Thanks in advance!

**Comment by alisterburt** [comment]
Hi @Koushouu - thanks for the issue! It looks like there's some problem with one of your tilt-series files, can it be opened in another program e.g 3dmod from IMOD? I would try to delete then regenerate the tilt series files from Warp

Good luck! FYI, if you have more issues I'm unlikely to respond for the next few days

**Comment by Koushouu** [comment]
Thanks @alisterburt ! I will try it later.

**Comment by Koushouu** [comment]
Its solved! I did as you suggested. Thank you
