### ISSUE TITLE
parameter <gaussfiltOutLierDetectionCC> not used yet

### ISSUE THREAD

**Issue by rnwokonko** [alisterburt/autoalign_dynamo#5]
I'm attempting to run dautoalign4warp, following the teamtomo tutorial using the EMPIAR-10164 data set. One issue that I am having however, is that the alignment is consistently failing at the gaussfiltOutlierDetectionCC.

Example:

Output checking is active for this step.
Cropping 2282 observations performed in 0.25 seconds
parameter <gaussfiltOutlierDetectionCC> not used yet
Starting first iteration
Killed

Is there an error log to help identify the issue, or has anyone else run into this problem?

**Comment by alisterburt** [comment]
Hi @rnwokonko - sorry you're running into issues!

I don't have any useful insight here unfortunately - only that this 'outlier detection' step has always thrown the same warning in my hands so I would be looking elsewhere for the problem, probably at my parallel computation setup

Assuming you're running on a cluster of some sort that is configured for multi-machine work, could you try to run on a single machine? There have been a few reports of clusters causing issues

**Comment by rnwokonko** [comment]
Hi @alisterburt,
I am in the process of setting up a new Windows 10 workstation for the lab, and was running through the teamtomo protocol to test and make sure Dynamo/Warp were configured properly. Dynamo is configured on windows subsystem for linux (wsl2). No luck in tracking down the issue over the weekend, but I will keep at it.

**Comment by alisterburt** [comment]
Good luck! It might be worth reaching out on the dynamo mailing list too 🙂

**Comment by alisterburt** [comment]
closing as stale - feel free to reopen if this comes up again
