### ISSUE TITLE
imregionalmax error

### ISSUE THREAD

**Issue by JuhaHuiskonen** [alisterburt/autoalign_dynamo#6]
Hello,

I am using atuoalign_dynamo in Matlab is R2021b. I get the error 
"Warning: Undefined function 'imregionalmax' for input arguments of type 'single'."

Is the Matlab version incompatible?  Any patch for this (we don't have any other version in our HPC environment). Thanks!

**Comment by alisterburt** [comment]
Hi Juha, thanks for the report! It looks like you're missing the computer vision toolbox in the HPC environment. 

I hope it won't be too much trouble to add it, these toolboxes and associated licensing issues were the main reason for my switch to Python for everything more recent... 🫠

**Comment by JuhaHuiskonen** [comment]
Hi Alister,  not sure if we can get the missing toolboxes to be added in the HPC environment. Is it possible to compile the app, with the required toolboxes?  So that the App could be used as a standalone like Dynamo's standalone version.

**Comment by alisterburt** [comment]
I haven't looked into compiling matlab code and no longer have easy access to (or interest in 😆) matlab so won't be spending time on putting that together

As an alternative you could 
1. copy the 'dautoalign4warp' function into its own script 
2. add the function arguments at the top
3. add a line running `/path/to/autoalign_activate.m` in the script so that the installation is added to the PATH
4. run the script using the dynamo standalone

This should hopefully allow you to get going with minimal effort

**Comment by JuhaHuiskonen** [comment]
Thanks - I understand.  I learned now that we have the required toolboxes, but only as a part of "MATLAB Parallel Server (MPS)". Is it possible to run your script using this?

**Comment by alisterburt** [comment]
I've never come across MPS so can't answer unfortunately! Good luck 🤞

**Comment by JuhaHuiskonen** [comment]
Thanks for the alternative solution, this seems feasible. I know how to run the script from Dynamo standalone. But could you give me a bit more information about how the script should look?  Specifically, I wasn't sure if I should modify dautoalign4warp.m? Or make a script.sh that calls this Matlab function (after first calling autoalign_activate.m and setting the input parameters)? Or something else?

**Comment by alisterburt** [comment]
A matlab script something like this, run from the standalone

I haven't tested this and know there are some issues with running scripts from the standalone which may crop up

```matlab
%%%%% Automatic on-the-fly alignment of a set of tilt series from Warp

%%% Parameters to be modified by user
% warp_imod_dir - directory 'imod' created by warp containing tilt series directories
% apix - pixel size in angstroms of tilt series
% fiducial_diameter_nm - fiducial diameter in nanometers
% nominal rotation angle - estimated tilt axis angle (CCW rotation from Y-axis)
% output folder - a folder in which to store the
% autoalign_installation_dir - path to directory into which autoalign_dynamo was installed

warp_imod_dir = 'imod';
apix = 1.35;
fiducial_diameter_nm = 10;
nominal_rotation_angle = 85.4;
output_folder = 'autoaligned';
autoalign_installation_dir = '/path/to/autoalign_install';

%%% Activate autoalign installation
autoalign_activate_script = fullfile(autoalign_installation_dir, 'autoalign_activate.m');
run(autoalign_activate_script);

%%% List of already processed tilt-series
processed = {};

%%% Attempt to
while true
    [ts_directory, processed] = next_dir(warp_imod_dir, processed);

    %
    if ischar(ts_directory)
        autoalign_sleep(processed)
        continue
    end

    % get paths to stack and rawtlt file
    [basename, stack, rawtlt] = ts_info_from_dir(ts_directory);

    % try to align tilt series
    if isfile(stack)
        try
            final_dir_name = autoalign(stack, basename, rawtlt, apix, fiducial_diameter_nm, output_folder);
            tiltalign(final_dir_name, nominal_rotation_angle, apix)
        catch ME
            handle_exception(ME)
        end
        autoalign_aux_cleanup()
        autoalign_summarise(output_folder)
    end
end




```

**Comment by alisterburt** [comment]
I'm going to close this as the requirement for the toolbox is specified in the README - good luck getting your tilt series aligned!
