### ISSUE TITLE
Only the dms file generated

### ISSUE THREAD

**Issue by smallelephant9516** [alisterburt/autoalign_dynamo#8]
It seems that the dms2mod function not working with the following error
point2model: command not found

**Comment by smallelephant9516** [comment]
What can be the potential solution.

**Comment by smallelephant9516** [comment]
Sorry, just notice that in the closed issue, let me check whether this can solve the problem

**Comment by alisterburt** [comment]
Hi @smallelephant9516 ! This means the imod program point2model is not present on your PATH, please check that IMOD is installed correctly

**Comment by smallelephant9516** [comment]
Thanks, using the tricks in #3 can solve the problem, so, this issue will be closed.
